# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='tasks.TaskLabel'),
        ),
        migrations.AddField(
            model_name='task',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskState'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('part_of', 'id')]),
        ),
    ]
